In [293]:
import psycopg2
from config import config
import pandas as pd
import os
import pickle
import re

In [ ]:
#Postgres Connection Setup
def connect(server):
    """ Connect to the PostgreSQL database server """
    conn = None
    try:
        # read connection parameters
        params = config(section=server)

        # connect to the PostgreSQL server
        #print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(**params)

        # create a cursor
        cur = conn.cursor()
        
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    
    return cur

def close():
    if conn is not None:
        conn.close()
        print('Database connection closed.')

In [352]:
def get_acs_table_metadata():
    """
    Searches existing tables in metadata schema that are sourced from the ACS to aggregate census variables and titles.
    
    Returns:
    -------------
    
    """
    
    #Establish connection to Postgres server
    cur = connect('sdvm') 

    #Matches on tables in metadata schema that include the string 'acs'.
    cur.execute(
        """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'metadata' AND table_name LIKE '%acs_m'
        ORDER BY table_name;
        """)

    #Assigns query results
    table_names = cur.fetchall()

    table_meta = pd.DataFrame(columns=['title', 'tbl_name', 'tbl_num', 'geography'])
    
    for idx, table in enumerate(table_names): 
        proc_table = table[0].replace("'", '')
        
        query = \
        """
        SELECT details 
        FROM metadata.{0}
        WHERE orderid IN (2, 4, 5, 6);
        """.format(proc_table)
        
        cur.execute(query)
        metadata = cur.fetchall()
        try:
            table_meta.loc[idx] = [x[0] for x in metadata]
        except ValueError:
            print("Error at " + str(table_names[idx]))
            continue

    cur.close()
    return table_meta

In [353]:
table_meta = get_acs_table_metadata()

Error at ('b16002_hh_linguistic_isolation_acs_m',)

In [354]:
#Uncomment to save new pickle of table_meta Dataframe
#pickle.dump(table_meta, open('pickles/table_meta.p', 'wb'))

In [ ]:
census_vars = pd.read_json('census_variables/variables.json', orient='index')
census_vars

In [ ]:
set(table_meta['title'])

In [355]:
len(list(table_meta['tbl_name']))

102

In [390]:

def get_col_names(sql_name, visited_ids, lines):
    #IDEA: continously add ids from visited_ids set and use "as" as a delimiter. Get all ids that came before delimiter
    #save what comes after delimiter as a hash map key and what comes before as values.
    
    hash_map = {}
    hash_map[sql_name] = {}
    list_ = []
    for line in lines:
        if "SELECT" in line:
            continue
        if "e._" in line:
            there = re.search('e._(.+?)]', line)
            if there:
                ids = [x for x in re.findall(r'\d+', there.group()) if len(x) == 3]
                list_ += ids
        
        #Once "as" is in line, hash the list of ids with the key of the term after the "as"
        if "as" in line: 
            there2 = re.search('as (.+?),', line)
            
            if there2:
                col_name = there2.group(1)
                if col_name.endswith(('m', 'me', 'mep')):
                    hash_map[sql_name][col_name] = {'ids':set(list_), 'moe': True}
                else:
                    hash_map[sql_name][col_name] = {'ids':set(list_), 'moe': False}  
                    
                if col_name.endswith(('p')):
                    hash_map[sql_name][col_name]['percent'] = True
                else:
                    hash_map[sql_name][col_name]['percent'] = False
            list_ = []
                
    return hash_map

In [ ]:
list(table_meta['tbl_name'])

In [421]:
ids_dict= {}
ids_dict_wo_names = {}

col_names_dict = {}
for root, dir, files in os.walk('K:\DataServices\Code\SQL\ACS\Tables', topdown=False):
    
    for name in files:
        name_wo_ext = name[:-4]
        
        if name_wo_ext not in list(table_meta['tbl_name']):
            continue
        if name.endswith(".sql"):
            start = False
            ids_dict[name_wo_ext] = []
            ids_dict_wo_names[name_wo_ext] = []
            with open(os.path.join(root, name)) as sql_file:
                lines = sql_file.readlines()
                visited_ids = set()
                for line in lines:
                    #print(line)
                    if('/*' in line):
                        start = True
                        continue
                    if('*/' in line):
                        break
                    if(start or '--' in line):
                        l = line.split('"')[1::2]; 
                        if(l and l[0] not in visited_ids):
                            visited_ids.add(l[0])
                            l[-1] = l[-1].replace('%', ' ')
                    
                            ids_dict[name_wo_ext].append(l)
                            ids_dict_wo_names[name_wo_ext].append(l[0])
                            
                col_names_dict.update(get_col_names(name_wo_ext, visited_ids, lines))
                
            sql_file.close()      


            ids_dict[name_wo_ext] = list(filter(None, ids_dict[name_wo_ext]))
            ids_dict_wo_names[name_wo_ext] = list(filter(None, ids_dict_wo_names[name_wo_ext]))

In [425]:
pickle.dump(ids_dict, open('table_to_censusid.p', 'wb'))

In [428]:
#col_names_dict['b01001_population_by_age_gender_acs_m']
pickle.dump(col_names_dict, open('cols_ids_dict.p', 'wb'))

[['001', 'Occupied housing units'], ['005', 'Occupied housing units Owner occupied: 2 vehicles available'], ['006', 'Occupied housing units Owner occupied: 3 vehicles available'], ['007', 'Occupied housing units Owner occupied: 4 vehicles available'], ['008', 'Occupied housing units Owner occupied: 5 or more vehicles available'], ['009', 'Occupied housing units Renter occupied:'], ['010', 'Occupied housing units Renter occupied: No vehicle available'], ['011', 'Occupied housing units Renter occupied: 1 vehicle available'], ['012', 'Occupied housing units Renter occupied: 2 vehicles available'], ['013', 'Occupied housing units Renter occupied: 3 vehicles available'], ['014', 'Occupied housing units Renter occupied: 4 vehicles available'], ['015', 'Occupied housing units Renter occupied: 5 or more vehicles available']]
[['001', 'Total population']]

IndexError: pop index out of range

In [286]:
table_ids = pd.DataFrame.from_dict(ids_dict, orient='index')

In [288]:
table_ids.dropna(how='all')
table_ids.sort_index()

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,160
b01001_population_by_age_gender_acs_m,"[001, SEX BY AGE for Total Population Total:]","[002, SEX BY AGE for Total Population Male:]","[003, SEX BY AGE for Total Population Male: ...","[004, SEX BY AGE for Total Population Male: ...","[005, SEX BY AGE for Total Population Male: ...","[006, SEX BY AGE for Total Population Male: ...","[007, SEX BY AGE for Total Population Male: ...","[008, SEX BY AGE for Total Population Male: ...","[009, SEX BY AGE for Total Population Male: ...","[010, SEX BY AGE for Total Population Male: ...",...,None,None,None,None,None,None,None,None,None,None
b01001a_whi_population_by_age_gender_acs_m,"[001, SEX BY AGE (WHITE ALONE) for People Who ...","[002, SEX BY AGE (WHITE ALONE) for People Who ...","[003, SEX BY AGE (WHITE ALONE) for People Who ...","[004, SEX BY AGE (WHITE ALONE) for People Who ...","[005, SEX BY AGE (WHITE ALONE) for People Who ...","[006, SEX BY AGE (WHITE ALONE) for People Who ...","[007, SEX BY AGE (WHITE ALONE) for People Who ...","[008, SEX BY AGE (WHITE ALONE) for People Who ...","[009, SEX BY AGE (WHITE ALONE) for People Who ...","[010, SEX BY AGE (WHITE ALONE) for People Who ...",...,None,None,None,None,None,None,None,None,None,None
b01001b_aa_population_by_age_gender_acs_m,"[001, SEX BY AGE (BLACK OR AFRICAN AMERICAN AL...","[002, SEX BY AGE (BLACK OR AFRICAN AMERICAN AL...","[003, SEX BY AGE (BLACK OR AFRICAN AMERICAN AL...","[004, SEX BY AGE (BLACK OR AFRICAN AMERICAN AL...","[005, SEX BY AGE (BLACK OR AFRICAN AMERICAN AL...","[006, SEX BY AGE (BLACK OR AFRICAN AMERICAN AL...","[007, SEX BY AGE (BLACK OR AFRICAN AMERICAN AL...","[008, SEX BY AGE (BLACK OR AFRICAN AMERICAN AL...","[009, SEX BY AGE (BLACK OR AFRICAN AMERICAN AL...","[010, SEX BY AGE (BLACK OR AFRICAN AMERICAN AL...",...,None,None,None,None,None,None,None,None,None,None
b01001c_na_population_by_age_gender_acs_m,"[001, SEX BY AGE (AMERICAN INDIAN AND ALASKA N...","[002, SEX BY AGE (AMERICAN INDIAN AND ALASKA N...","[003, SEX BY AGE (AMERICAN INDIAN AND ALASKA N...","[004, SEX BY AGE (AMERICAN INDIAN AND ALASKA N...","[005, SEX BY AGE (AMERICAN INDIAN AND ALASKA N...","[006, SEX BY AGE (AMERICAN INDIAN AND ALASKA N...","[007, SEX BY AGE (AMERICAN INDIAN AND ALASKA N...","[008, SEX BY AGE (AMERICAN INDIAN AND ALASKA N...","[009, SEX BY AGE (AMERICAN INDIAN AND ALASKA N...","[010, SEX BY AGE (AMERICAN INDIAN AND ALASKA N...",...,None,None,None,None,None,None,None,None,None,None
b01001d_as_population_by_age_gender_acs_m,"[001, SEX BY AGE (ASIAN ALONE) for People Who ...","[002, SEX BY AGE (ASIAN ALONE) for People Who ...","[003, SEX BY AGE (ASIAN ALONE) for People Who ...","[004, SEX BY AGE (ASIAN ALONE) for People Who ...","[005, SEX BY AGE (ASIAN ALONE) for People Who ...","[006, SEX BY AGE (ASIAN ALONE) for People Who ...","[007, SEX BY AGE (ASIAN ALONE) for People Who ...","[008, SEX BY AGE (ASIAN ALONE) for People Who ...","[009, SEX BY AGE (ASIAN ALONE) for People Who ...","[010, SEX BY AGE (ASIAN ALONE) for People Who ...",...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
b27001_healthinsurance_by_gender_age_acs_m,"[001, Total:]","[002, Total: Male:]","[003, Total: Male: Under 6 years:]","[004, Total: Male: Under 6 years: With heal...","[005, Total: Male: Under 6 years: No health...","[006, Total: Male: 6 to 17 years:]","[007, Total: Male: 6 to 17 years: With heal...","[008, Total: Male: 6 to 17 years: No health...","[009, Total: Male: 18 to 24 years:]","[010, Total: Male: 18 to 24 years: With hea...",...,None,None,None,None,None,None,None,None,None,None
c15002_educational_attainment_by_race_acs_m,"[001, White alone population 25 years and over]","[002, White alone population 25 years and over...","[003, White alone population 25 years and over...","[004, White alone population 25 years and over...","[005, White alone population 25 years and over...","[006, White alone population 25 years and over...","[007, White alone population 25 years and over...","[008, White alone population 25 years and over...","[009, White alone population 25 years and over...","[010, White alone population 25 years and over...",...,None,None,None,None,None,None,None,None,None,None
c15002_educational_attainment_by_race_acs_msa,"[001, White alone population 25 years and over]","[002, White alone population 25 years and over...","[003, White alone population 25 years and over...","[004, White alone population 25 years and over...","[005, White alone population 25 years and over...","[006, White alone population 25 years and over...","[007, White alone population 25 years and over...","[008, White alone population 25 years and over...","[009, White alone population 25 years and over...","[010, White alone population 25 years and over...",...,None,None,None,None,None,None,None,None,None,None
c18120_emp_status_by_disability_status_acs_m,"[001, EMPLOYMENT STATUS BY DISABILITY STATUS f...","[002, EMPLOYMENT STATUS BY DISABILITY STATUS f...","[003, EMPLOYMENT STATUS BY DISABILITY STATUS f...","[004, EMPLOYMENT STATUS BY DISABILITY STATUS f...","[005, EMPLOYMENT STATUS BY DISABILITY STATUS f...","[006, EMPLOYMENT STATUS BY DISABILITY STATUS f...","[007, EMPLOYMENT STATUS BY DISABILITY STATUS f...","[008, EMPLOYMENT STATUS BY DISABILITY STATUS f...","[009, EMPLOYMENT STATUS BY DISABILITY STATUS f...","[010, EMPLOYMENT STATUS BY DISABILITY STATUS f...",...,None,None,None,None,None,None,None,None,None,None
c18130_poverty_status_by_disability_status_acs_m,"[001, AGE BY DISABILITY STATUS BY POVERTY STAT...","[002, AGE BY DISABILITY STATUS BY POVERTY STAT...","[003, AGE BY DISABILITY STATUS BY POVERTY STAT...","[004, AGE BY DISABILITY STATUS BY POVERTY STAT...","[005, AGE BY DISABILITY STATUS BY POVERTY STAT...","[006, AGE BY DISABILITY STATUS BY POVERTY STAT...","[007, AGE BY DISABILITY STATUS BY POVERTY STAT...","[008, AGE BY DISABILITY STATUS BY POVERTY STAT...","[009, AGE BY DISABILITY STATUS BY POVERTY STAT...","[010, AGE BY DISABILITY STATUS BY POVERTY STAT...",...,None,None,None,None,None,None,None,None,None,None

In [408]:
#table_ids.sort_index().index.values
table_ids.loc['b01001_population_by_age_gender_acs_m', 0]

['001', 'SEX BY AGE for Total Population  Total:']